Add net6.0
happy-travel/consul-key-value-client pull request #10
Opened 2021-12-05 19:59 UTC by oleg-n-k

Add net6.0

2021-12-06 01:42 UTC, DFSko approved these changes

2021-12-06 01:42 UTC, DFSko commented on HappyTravel.ConsulKeyValueClient.Abstractions/HappyTravel.ConsulKeyValueClient.Abstractions.csproj
> +    <TargetFrameworks>net5.0;net6.0;netcoreapp3.1</TargetFrameworks>
Maybe drop 3.1?

2021-12-06 01:42 UTC, DFSko commented on HappyTravel.ConsulKeyValueClient.ConfigurationProvider/HappyTravel.ConsulKeyValueClient.ConfigurationProvider.csproj
> +        <TargetFrameworks>net5.0;net6.0;netcoreapp3.1</TargetFrameworks>
Maybe drop 3.1?

2021-12-06 01:42 UTC, DFSko commented on HappyTravel.ConsulKeyValueClient.ConsulClient/HappyTravel.ConsulKeyValueClient.ConsulClient.csproj
> +    <TargetFrameworks>net5.0;net6.0;netcoreapp3.1</TargetFrameworks>
Maybe drop 3.1?

2021-12-06 01:42 UTC, DFSko commented on HappyTravel.ConsulKeyValueClient.FileSettingsProvider/HappyTravel.ConsulKeyValueClient.FileSettingsProvider.csproj
> +    <TargetFrameworks>net5.0;net6.0;netcoreapp3.1</TargetFrameworks>
Maybe drop 3.1?

2021-12-06 01:42 UTC, DFSko commented on HappyTravel.ConsulKeyValueClient.KvUpdater/HappyTravel.ConsulKeyValueClient.KvUpdater.csproj
> +    <TargetFrameworks>net5.0;net6.0;netcoreapp3.1</TargetFrameworks>
Maybe drop 3.1?

2021-12-06 01:42 UTC, DFSko commented on HappyTravel.ConsulKeyValueClient/HappyTravel.ConsulKeyValueClient.csproj
> +    <TargetFrameworks>net5.0;net6.0;netcoreapp3.1</TargetFrameworks>
Maybe drop 3.1?

2021-12-06 13:28 UTC, kirillta requested changes
Please, exclude ` .DS_Store` files from the PR

2021-12-07 07:35 UTC, hasmikharutyunyan approved these changes

2021-12-07 09:56 UTC, oleg-n-k commented on HappyTravel.ConsulKeyValueClient.Abstractions/HappyTravel.ConsulKeyValueClient.Abstractions.csproj
> +    <TargetFrameworks>net5.0;net6.0;netcoreapp3.1</TargetFrameworks>
fixed

2021-12-07 09:56 UTC, oleg-n-k commented on HappyTravel.ConsulKeyValueClient.ConfigurationProvider/HappyTravel.ConsulKeyValueClient.ConfigurationProvider.csproj
> +        <TargetFrameworks>net5.0;net6.0;netcoreapp3.1</TargetFrameworks>
fixed

2021-12-07 09:56 UTC, oleg-n-k commented on HappyTravel.ConsulKeyValueClient.ConsulClient/HappyTravel.ConsulKeyValueClient.ConsulClient.csproj
> +    <TargetFrameworks>net5.0;net6.0;netcoreapp3.1</TargetFrameworks>
fixed

2021-12-07 09:56 UTC, oleg-n-k commented on HappyTravel.ConsulKeyValueClient.KvUpdater/HappyTravel.ConsulKeyValueClient.KvUpdater.csproj
> +    <TargetFrameworks>net5.0;net6.0;netcoreapp3.1</TargetFrameworks>
fixed

2021-12-07 09:56 UTC, oleg-n-k commented on HappyTravel.ConsulKeyValueClient/HappyTravel.ConsulKeyValueClient.csproj
> +    <TargetFrameworks>net5.0;net6.0;netcoreapp3.1</TargetFrameworks>
fixed

2021-12-07 09:58 UTC, kirillta approved these changes

2021-12-07 10:38 UTC, merged